services:
  kimai:
    build:
      context: .docker/php
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - ADMINMAIL=${ADMINMAIL:-kimai@example.com}
      - ADMINPASS=${ADMINPASS:-password}
      - DB_ADAPTER=${DB_ADAPTER:-mysql}
      - DB_NAME=${DB_NAME:-kimai}
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWD=${DB_PASSWD:-root}
      - DATABASE_URL=${DATABASE_URL:-${DB_ADAPTER:-mysql}://${DB_USER:-root}:${DB_PASSWD:-root}@${DB_HOST:-mysql}:${DB_PORT:-3306}/${DB_NAME:-kimai}}
      - TRUSTED_HOSTS=${TRUSTED_HOSTS:-nginx,localhost,127.0.0.1}
      - MAILER_URL=${MAILER_URL:-smtp://mailer:1025}
      - MAILER_FROM=${MAILER_FROM:-kimai@example.com}
      - XDEBUG_CONFIG=${XDEBUG_CONFIG:-client_host=172.17.0.1 client_port=9003 start_with_request=yes log_level=0 discover_client_host=true}
      - XDEBUG_MODE=${XDEBUG_MODE:-off}
      - TZ=${TZ:-America/Sao_Paulo}
    volumes:
      - ~/.composer:/root/.composer/
      - ./volumes/php:/opt/kimai
      - ./volumes/php/var:/opt/kimai/var
    restart: unless-stopped
  nginx:
    image: tobybatch/nginx-fpm-reverse-proxy
    restart: unless-stopped
    volumes:
      - ./volumes/php/public:/opt/kimai/public:ro
    ports:
      - 80:80
    depends_on:
      - kimai
    healthcheck:
      test:  wget --spider http://nginx/health || exit 1
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
  mysql:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-kimai}
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h localhost
      interval: 20s
      start_period: 10s
      timeout: 10s
      retries: 3
